export const featuredStories = [
  {
    id: 1,
    img: 'https://flowmountainbike.com/wp-content/uploads/2012/11/WEB_Feature_SIN_Masthead-1-1600x650.jpg',
    title: 'Strength In Numbers',
    createdAt: 'NOV. 12TH 2019',
    readTime: 3,
    content: 'The larger-than-life Arab-American music producer and DJ is known for and DJ is known',
    hashtags: ['Strength', 'Support System', 'tag3', 'tag4'],
    likes: 10,
    loves: 20,
    neutrals: 30,
    sads: 10,
    claps: 22,
    featured: true,
    author: "Aesus ist",
    bookmarked: false
  },
  {
    id: 2,
    img: 'https://lumiere-a.akamaihd.net/v1/images/b_toystory2_header_mobile_17813_be9f26d8.jpeg?region=0,0,640,320',
    title: 'Story 2',
    createdAt: 'NOV. 12TH 2019',
    readTime: 3,
    content: 'The larger-than-life Arab-American music producer and DJ is known for and DJ is known',
    hashtags: ['Strength', 'Support System', 'tag3', 'tag4'],
    likes: 34,
    loves: 5,
    neutrals: 3,
    sads: 20,
    claps: 32,
    featured: true,
    author: "James Bond",
    bookmarked: true
  },
  {
    id: 3,
    img: 'https://i.dailymail.co.uk/1s/2018/12/14/12/7425330-6496081-image-a-1_1544790325933.jpg',
    title: 'Story 3',
    createdAt: 'NOV. 12TH 2019',
    readTime: 3,
    content: 'The larger-than-life Arab-American music producer and DJ is known for and DJ is known',
    hashtags: ['Strength', 'Support System', 'tag3', 'tag4'],
    likes: 10,
    loves: 20,
    neutrals: 30,
    sads: 10,
    claps: 22,
    featured: true,
    author: "Hello Kitty",
    bookmarked: true
  },
]